const processLookup = [
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1159",
    "output_item": "G1272",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1122",
    "output_item": "G1136",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1161",
    "output_item": "G1279",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1196",
    "output_item": "G1284",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1204",
    "output_item": "G1212",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1249",
    "output_item": "G1229",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1160",
    "output_item": "G1177",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1194",
    "output_item": "G1267",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1195",
    "output_item": "G1266",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1236",
    "output_item": "G1265",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1291",
    "output_item": "G1169",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1229",
    "output_item": "G1226",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G5004",
    "output_item": "G1176",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1229",
    "output_item": "G1304",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G5006",
    "output_item": "G1208",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G5012",
    "output_item": "G1252",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G5014",
    "output_item": "G1317",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1242",
    "output_item": "G1325",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1122",
    "output_item": "G1147",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1248",
    "output_item": "G1287",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1230",
    "output_item": "G1327",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1168",
    "output_item": "G1211",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1122",
    "output_item": "G1149",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1121",
    "output_item": "G1333",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1194",
    "output_item": "G1340",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1222",
    "output_item": "G1342",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1222",
    "output_item": "G1346",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1198",
    "output_item": "G1348",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1224",
    "output_item": "G12241",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  },
  {
    "process_code": 8,
    "shortcode": "SL",
    "process_name": "Slicing parts for slices, portion",
    "intake_item": "G1224",
    "output_item": "G12242",
    "input_location": "1570",
    "output_location": "1570",
    "production_order_series": "P08",
    "process_loss": 0
  }
];

export default processLookup;